# Alcoen Website - Caddy Configuration Template
# This template is dynamically populated by deploy.sh.
# Do not edit this file directly on the server; edit deploy.sh instead.

# Placeholder values:
#   {{DOMAIN}}    - IP address or domain name
#   {{TLS}}       - "tls internal" for IP, empty for domain

{{DOMAIN}} {
    encode gzip
    reverse_proxy localhost:3000
    {{TLS}}
}
